from core.action.action_framework.registry import action

@action(
    name="describe_screen",
    description="Captures the entire screen and converts it into an LLM-friendly, markdown description.",
    mode="GUI",
    action_sets=["gui_interaction"],
    input_schema={},
    output_schema={
        "status": {
            "type": "string",
            "example": "success",
            "description": "'success' if the screen was described, 'error' otherwise."
        },
        "description": {
            "type": "string",
            "example": "The screen shows a Windows desktop with a taskbar at the bottom...",
            "description": "Markdown-friendly description generated by the VLM."
        },
        "file_path": {
            "type": "string",
            "example": "C:\\\\workspace\\\\viewscreen_20250801_091500.png",
            "description": "Path to the captured screenshot."
        },
        "message": {
            "type": "string",
            "example": "Unexpected error.",
            "description": "Error message if applicable."
        }
    },
    test_payload={
        "simulated_mode": False
    }
)
def view_screen(input_data: dict) -> dict:
    import json
    import core.internal_action_interface as iai
    
    simulated_mode = input_data.get('simulated_mode', False)

    try:
        if not simulated_mode:
            result = iai.InternalActionInterface.describe_screen()
        else:
            result = {'status': 'ok', 'description': 'Test screen description', 'file_path': '/tmp/test_screen.png'}
        return {'status': 'success', 'description': result.get('description', ''), 'file_path': result.get('file_path', ''), 'message': ''}
    except Exception as e:
        return {'status': 'error', 'description': '', 'file_path': '', 'message': str(e)}